import {
  CONCEICAO_CITIZEN_ADDRESS,
  DEMO_CITIZEN_ADDRESS,
} from '../../shared/src/constants.js';

export { DEMO_CITIZEN_ADDRESS, CONCEICAO_CITIZEN_ADDRESS };

const neighborhoods = [
  {
    id: 'sape',
    nome: 'Sape',
    adjacentes: ['centro', 'corrego-feijao'],
    populacao: 4800,
    repoSlug: 'sape-zoneamento',
  },
  {
    id: 'centro',
    nome: 'Centro',
    adjacentes: ['sape', 'conceicao-itagua'],
    populacao: 7200,
    repoSlug: 'centro-urbano',
  },
  {
    id: 'conceicao-itagua',
    nome: 'Conceicao de Itagua',
    adjacentes: ['centro', 'corrego-feijao'],
    populacao: 3900,
    repoSlug: 'conceicao-meio-ambiente',
  },
  {
    id: 'corrego-feijao',
    nome: 'Corrego do Feijao',
    adjacentes: ['sape', 'conceicao-itagua'],
    populacao: 2600,
    repoSlug: 'corrego-recuperacao',
  },
];

const commits = [
  {
    id: 'commit-lo-001',
    leiId: 'lei-organica',
    hash: '0x0000genesis1',
    mensagem: 'genesis: publica lei organica municipal de Brumadinho',
    autor: '0xPrefeituraBrumadinho000000000000000000000001',
    timestamp: '2026-01-01T00:00:00Z',
    versao: '3.0.0',
    resumo:
      'Publicacao inicial da Lei Organica Municipal como repositorio raiz do sistema GitLaw. Define soberania popular, direitos de participacao, estrutura de bairros e as regras de emenda constitucional.',
    articleChanges: [],
  },
  {
    id: 'commit-001',
    leiId: 'lei-1',
    hash: '0x4b1f47aa1',
    mensagem: 'Publica versao auditavel do plano diretor',
    autor: '0xPrefeituraBrumadinho000000000000000000000001',
    timestamp: '2026-01-10T10:00:00Z',
    versao: '4.2.0',
    resumo: 'Consolida o texto base do Plano Diretor para consulta publica.',
    articleChanges: [],
  },
  {
    id: 'commit-002',
    leiId: 'lei-2',
    hash: '0x9d2a1ff20',
    mensagem: 'Consolida codigo de obras municipal',
    autor: '0xPrefeituraBrumadinho000000000000000000000001',
    timestamp: '2026-01-12T09:15:00Z',
    versao: '2.1.4',
    resumo: 'Publica a base versionada do Codigo de Obras com artigos rastreaveis.',
    articleChanges: [],
  },
  {
    id: 'commit-003',
    leiId: 'lei-4',
    hash: '0x7cf236da0',
    mensagem: 'Publica estatuto do pedestre',
    autor: '0xPrefeituraBrumadinho000000000000000000000001',
    timestamp: '2026-01-14T13:45:00Z',
    versao: '1.0.3',
    resumo: 'Versiona a politica de prioridade ao pedestre nas vias municipais.',
    articleChanges: [],
  },
  {
    id: 'commit-004',
    leiId: 'lei-3',
    hash: '0xae92f7bc4',
    mensagem: 'Consolida politica ambiental municipal',
    autor: '0xPrefeituraBrumadinho000000000000000000000001',
    timestamp: '2026-01-18T11:20:00Z',
    versao: '1.8.1',
    resumo: 'Versiona diretrizes ambientais para consulta, emenda e auditoria.',
    articleChanges: [],
  },
  {
    id: 'commit-005',
    leiId: 'lei-fork-1',
    hash: '0xbad4f0rk1',
    mensagem: 'variacao local: inicializa experimento de uso misto no Sape',
    autor: DEMO_CITIZEN_ADDRESS,
    timestamp: '2026-03-10T09:15:00Z',
    versao: '1.0.0',
    resumo: 'Cria a variacao local do Codigo de Obras com ajustes territoriais no Sape.',
    articleChanges: [],
  },
  {
    id: 'commit-006',
    leiId: 'lei-3',
    prId: 'pr-103',
    hash: '0x11a44c77e',
    mensagem: 'Cria incentivo para captacao de agua da chuva',
    autor: CONCEICAO_CITIZEN_ADDRESS,
    timestamp: '2026-03-01T09:15:00Z',
    versao: '1.8.2',
    resumo: 'Aprovacao municipal do incentivo fiscal para imoveis com captacao de agua da chuva.',
    articleChanges: [
      {
        articleId: 'lei-3-art-8',
        rotulo: 'Art. 8o',
        before:
          'O Municipio podera incentivar boas praticas ambientais por meio de programas de educacao e certificacao voluntaria.',
        after:
          'O Municipio podera incentivar boas praticas ambientais por meio de programas de educacao, certificacao voluntaria e isencao parcial de IPTU para imoveis com captacao de agua da chuva, nos termos do regulamento.',
      },
    ],
  },
];

const laws = [
  {
    id: 'lei-organica',
    titulo: 'Lei Organica do Municipio de Brumadinho',
    numero: 'Lei Organica Municipal / 1990',
    categoria: 'constituicao',
    versao: '3.0.0',
    atualizadaEm: '2026-01-01T00:00:00Z',
    resumo:
      'Constituicao municipal de Brumadinho. Define a estrutura de poder, os direitos fundamentais dos cidadaos e as regras basicas de participacao democratica.',
    isRoot: true,
    quorumEspecial: 0.67,
    artigos: [
      {
        id: 'lo-art-1',
        rotulo: 'Art. 1o',
        texto:
          'O Municipio de Brumadinho, pessoa juridica de direito publico interno, exerce sua autonomia nos termos da Constituicao Federal, da Constituicao do Estado de Minas Gerais e desta Lei Organica.',
        ultimaAtualizacaoEm: '2026-01-01T00:00:00Z',
        ultimoAutor: '0xPrefeituraBrumadinho000000000000000000000001',
        ultimoCommitId: 'commit-lo-001',
      },
      {
        id: 'lo-art-2',
        rotulo: 'Art. 2o',
        texto:
          'Todo poder emana do povo. No GitLaw, o cidadao registrado exerce diretamente o poder de propor, debater e votar alteracoes nas normas municipais, de forma rastreavel e auditavel.',
        ultimaAtualizacaoEm: '2026-01-01T00:00:00Z',
        ultimoAutor: '0xPrefeituraBrumadinho000000000000000000000001',
        ultimoCommitId: 'commit-lo-001',
      },
      {
        id: 'lo-art-3',
        rotulo: 'Art. 3o',
        texto:
          'Sao principios fundamentais do Municipio: a soberania popular, a dignidade da pessoa humana, a transparencia administrativa, a funcao social da propriedade e a sustentabilidade ambiental.',
        ultimaAtualizacaoEm: '2026-01-01T00:00:00Z',
        ultimoAutor: '0xPrefeituraBrumadinho000000000000000000000001',
        ultimoCommitId: 'commit-lo-001',
      },
      {
        id: 'lo-art-10',
        rotulo: 'Art. 10',
        texto:
          'Sao direitos do cidadao registrado: participar das deliberacoes publicas, acessar o historico completo de qualquer alteracao normativa, propor emendas a leis ordinarias e votar com peso proporcional ao seu vinculo territorial.',
        ultimaAtualizacaoEm: '2026-01-01T00:00:00Z',
        ultimoAutor: '0xPrefeituraBrumadinho000000000000000000000001',
        ultimoCommitId: 'commit-lo-001',
      },
      {
        id: 'lo-art-25',
        rotulo: 'Art. 25',
        texto:
          'O Municipio e organizado em bairros com autonomia participativa. Cada bairro pode propor variacoes locais de leis ordinarias, desde que nao contrariem esta Lei Organica nem o Plano Diretor.',
        ultimaAtualizacaoEm: '2026-01-01T00:00:00Z',
        ultimoAutor: '0xPrefeituraBrumadinho000000000000000000000001',
        ultimoCommitId: 'commit-lo-001',
      },
      {
        id: 'lo-art-40',
        rotulo: 'Art. 40',
        texto:
          'O orcamento municipal sera anualmente votado pela cidadania ativa, com prioridades definidas por bairro e consolidadas em votacao ponderada de alcance municipal.',
        ultimaAtualizacaoEm: '2026-01-01T00:00:00Z',
        ultimoAutor: '0xPrefeituraBrumadinho000000000000000000000001',
        ultimoCommitId: 'commit-lo-001',
      },
      {
        id: 'lo-art-60',
        rotulo: 'Art. 60',
        texto:
          'Esta Lei Organica somente podera ser emendada por proposta aprovada com quorum minimo de dois teros dos cidadaos ativos, respeitado periodo de 30 dias de debate publico antes da votacao.',
        ultimaAtualizacaoEm: '2026-01-01T00:00:00Z',
        ultimoAutor: '0xPrefeituraBrumadinho000000000000000000000001',
        ultimoCommitId: 'commit-lo-001',
      },
    ],
    commitIds: ['commit-lo-001'],
  },
  {
    id: 'lei-1',
    titulo: 'Plano Diretor Estrategico',
    numero: 'Lei Complementar 105/2014',
    categoria: 'urbanismo',
    versao: '4.2.0',
    atualizadaEm: '2026-02-15T10:00:00Z',
    resumo:
      'Repositorio raiz de zoneamento, uso e ocupacao do solo. Toda proposta de alteracao territorial deve ter este documento como alvo e exige quorum qualificado.',
    isRoot: true,
    quorumEspecial: 0.6,
    artigos: [
      {
        id: 'lei-1-art-1',
        rotulo: 'Art. 1o',
        texto:
          'Esta Lei orienta o desenvolvimento urbano de Brumadinho, equilibrando habitacao, mobilidade, atividade economica e preservacao ambiental.',
        ultimaAtualizacaoEm: '2026-01-10T10:00:00Z',
        ultimoAutor: '0xPrefeituraBrumadinho000000000000000000000001',
        ultimoCommitId: 'commit-001',
      },
      {
        id: 'lei-1-art-2',
        rotulo: 'Art. 2o',
        texto:
          'A politica urbana devera observar a funcao social da cidade, a participacao cidada e a transparencia na revisao das normas.',
        ultimaAtualizacaoEm: '2026-01-10T10:00:00Z',
        ultimoAutor: '0xPrefeituraBrumadinho000000000000000000000001',
        ultimoCommitId: 'commit-001',
      },
    ],
    commitIds: ['commit-001'],
  },
  {
    id: 'lei-2',
    titulo: 'Codigo de Obras e Edificacoes',
    numero: 'Lei 16.642/2017',
    categoria: 'urbanismo',
    versao: '2.1.4',
    atualizadaEm: '2026-01-12T09:15:00Z',
    resumo: 'Estabelece padroes de seguranca, acessibilidade e sustentabilidade para obras no municipio.',
    artigos: [
      {
        id: 'lei-2-art-4',
        rotulo: 'Art. 4o',
        texto:
          'Projetos de edificacoes deverao demonstrar conformidade com as normas municipais de acessibilidade antes da aprovacao.',
        ultimaAtualizacaoEm: '2026-01-12T09:15:00Z',
        ultimoAutor: '0xPrefeituraBrumadinho000000000000000000000001',
        ultimoCommitId: 'commit-002',
      },
      {
        id: 'lei-2-art-12',
        rotulo: 'Art. 12',
        texto:
          'Novos empreendimentos comerciais poderao adotar solucoes sustentaveis facultativas para drenagem e conforto termico.',
        ultimaAtualizacaoEm: '2026-01-12T09:15:00Z',
        ultimoAutor: '0xPrefeituraBrumadinho000000000000000000000001',
        ultimoCommitId: 'commit-002',
      },
    ],
    commitIds: ['commit-002'],
  },
  {
    id: 'lei-3',
    titulo: 'Politica Municipal de Meio Ambiente',
    numero: 'Lei 14.887/2009',
    categoria: 'meio-ambiente',
    versao: '1.8.2',
    atualizadaEm: '2026-03-01T09:15:00Z',
    resumo: 'Diretrizes para protecao, conservacao e recuperacao ambiental com historico publico de alteracoes.',
    artigos: [
      {
        id: 'lei-3-art-8',
        rotulo: 'Art. 8o',
        texto:
          'O Municipio podera incentivar boas praticas ambientais por meio de programas de educacao, certificacao voluntaria e isencao parcial de IPTU para imoveis com captacao de agua da chuva, nos termos do regulamento.',
        ultimaAtualizacaoEm: '2026-03-01T09:15:00Z',
        ultimoAutor: CONCEICAO_CITIZEN_ADDRESS,
        ultimoCommitId: 'commit-006',
      },
      {
        id: 'lei-3-art-14',
        rotulo: 'Art. 14',
        texto:
          'Projetos de recuperacao ambiental em areas sensiveis deverao prever monitoramento publico dos indicadores de solo e agua.',
        ultimaAtualizacaoEm: '2026-01-18T11:20:00Z',
        ultimoAutor: '0xPrefeituraBrumadinho000000000000000000000001',
        ultimoCommitId: 'commit-004',
      },
    ],
    commitIds: ['commit-004', 'commit-006'],
  },
  {
    id: 'lei-4',
    titulo: 'Estatuto do Pedestre',
    numero: 'Lei 16.673/2017',
    categoria: 'transporte',
    versao: '1.0.3',
    atualizadaEm: '2026-01-14T13:45:00Z',
    resumo: 'Garante prioridade, seguranca e conforto ao pedestre com votacao rastreavel por proposta.',
    artigos: [
      {
        id: 'lei-4-art-4',
        rotulo: 'Art. 4o',
        texto:
          'A largura minima das calcadas sera de 1,20m, observadas as condicoes de seguranca e acessibilidade fixadas em regulamento.',
        ultimaAtualizacaoEm: '2026-01-14T13:45:00Z',
        ultimoAutor: '0xPrefeituraBrumadinho000000000000000000000001',
        ultimoCommitId: 'commit-003',
      },
      {
        id: 'lei-4-art-7',
        rotulo: 'Art. 7o',
        texto:
          'Intervencoes viarias deverao manter travessias seguras, iluminadas e sinalizadas durante toda a obra.',
        ultimaAtualizacaoEm: '2026-01-14T13:45:00Z',
        ultimoAutor: '0xPrefeituraBrumadinho000000000000000000000001',
        ultimoCommitId: 'commit-003',
      },
    ],
    commitIds: ['commit-003'],
  },
  {
    id: 'lei-fork-1',
    titulo: 'Codigo de Obras (Variacao Sape)',
    numero: 'Exp-001/Sape',
    categoria: 'urbanismo',
    versao: '1.0.0',
    atualizadaEm: '2026-03-10T09:15:00Z',
    resumo: 'Adaptacao local do Codigo de Obras para uso misto e comercio de baixo impacto no bairro Sape.',
    isFork: true,
    bairroId: 'sape',
    bairroNome: 'Sape',
    leiOrigemId: 'lei-2',
    artigos: [
      {
        id: 'lei-fork-1-art-4',
        rotulo: 'Art. 4o',
        texto:
          'Projetos de edificacoes no Sape deverao demonstrar conformidade com acessibilidade e com a topografia local antes da aprovacao.',
        ultimaAtualizacaoEm: '2026-03-10T09:15:00Z',
        ultimoAutor: DEMO_CITIZEN_ADDRESS,
        ultimoCommitId: 'commit-005',
      },
      {
        id: 'lei-fork-1-art-18',
        rotulo: 'Art. 18',
        texto:
          'Fica permitido comercio de baixo impacto em vias residenciais previamente definidas no plano local do experimento, mediante licenca simplificada.',
        ultimaAtualizacaoEm: '2026-03-10T09:15:00Z',
        ultimoAutor: DEMO_CITIZEN_ADDRESS,
        ultimoCommitId: 'commit-005',
      },
    ],
    commitIds: ['commit-005'],
  },
];

const citizens = [
  {
    address: DEMO_CITIZEN_ADDRESS,
    bairroId: 'sape',
    bairroNome: 'Sape',
    nivel: 3,
    emitidoEm: '2026-01-15T10:00:00Z',
    ativo: true,
    verificadoEm: '2026-01-15T10:00:00Z',
  },
  {
    address: '0x71bE63f3384f5fb98995898A86B02Fb2426c5788',
    bairroId: 'centro',
    bairroNome: 'Centro',
    nivel: 4,
    emitidoEm: '2026-01-18T11:00:00Z',
    ativo: true,
    verificadoEm: '2026-01-18T11:00:00Z',
  },
  {
    address: CONCEICAO_CITIZEN_ADDRESS,
    bairroId: 'conceicao-itagua',
    bairroNome: 'Conceicao de Itagua',
    nivel: 2,
    emitidoEm: '2026-01-20T09:30:00Z',
    ativo: true,
    verificadoEm: '2026-01-20T09:30:00Z',
  },
];

const forks = [
  {
    id: 'fork-1',
    slug: 'sape-zoneamento-misto',
    nome: 'Zoneamento Misto - Sape',
    bairroId: 'sape',
    bairroNome: 'Sape',
    leiOrigemId: 'lei-2',
    leiForkId: 'lei-fork-1',
    objetivo:
      'Permitir comercio de baixo impacto em ruas residenciais para fortalecer a economia local sem perder controle urbano.',
    duracaoMeses: 6,
    criadoEm: '2026-03-10T09:15:00Z',
    autor: DEMO_CITIZEN_ADDRESS,
    status: 'ativo',
    participantes: 450,
    proposalIds: ['pr-201'],
    sourceProposalId: 'pr-104',
  },
];

const proposals = [
  {
    id: 'pr-101',
    kind: 'emenda',
    titulo: 'Exige cobertura vegetal em novos comercios',
    leiAlvoId: 'lei-2',
    leiAlvoNome: 'Codigo de Obras e Edificacoes',
    artigoAlvoId: 'lei-2-art-12',
    artigoAlvoRotulo: 'Art. 12',
    status: 'em-revisao',
    autor: '0x71bE63f3384f5fb98995898A86B02Fb2426c5788',
    bairroId: 'centro',
    bairroNome: 'Centro',
    criadoEm: '2026-03-15T08:00:00Z',
    justificativa:
      'Reduzir ilhas de calor e melhorar a drenagem pluvial em areas mais adensadas do municipio.',
    issueId: '#44',
    urgencia: false,
    txHash: '0xabc123def456',
    impactedNeighborhoodIds: ['centro', 'sape'],
    ci: {
      conflito: true,
      orcamento: true,
      constitucional: true,
      redacao: true,
    },
    oldText:
      'Novos empreendimentos comerciais poderao adotar solucoes sustentaveis facultativas para drenagem e conforto termico.',
    newText:
      'Novos empreendimentos comerciais com area acima de 300m2 deverao prever telhados verdes ou solucao equivalente de conforto termico e drenagem, conforme regulamento tecnico municipal.',
    quorum: 2.2,
    votingEndsAt: '2026-03-29T08:00:00Z',
    votes: [
      {
        address: '0x71bE63f3384f5fb98995898A86B02Fb2426c5788',
        choice: 'favor',
        weight: 1,
        bairroId: 'centro',
        bairroNome: 'Centro',
        createdAt: '2026-03-15T09:00:00Z',
      },
      {
        address: CONCEICAO_CITIZEN_ADDRESS,
        choice: 'contra',
        weight: 0.3,
        bairroId: 'conceicao-itagua',
        bairroNome: 'Conceicao de Itagua',
        createdAt: '2026-03-15T12:10:00Z',
      },
    ],
    comments: [
      {
        id: 'comment-1',
        authorAddress: DEMO_CITIZEN_ADDRESS,
        createdAt: '2026-03-15T15:20:00Z',
        body: 'Vale incluir criterio tecnico para cobertura equivalente, evitando engessar pequenos estabelecimentos.',
      },
    ],
    source: 'municipal',
  },
  {
    id: 'pr-102',
    kind: 'emenda',
    titulo: 'Amplia largura minima em vias arteriais',
    leiAlvoId: 'lei-4',
    leiAlvoNome: 'Estatuto do Pedestre',
    artigoAlvoId: 'lei-4-art-4',
    artigoAlvoRotulo: 'Art. 4o',
    status: 'aberto',
    autor: '0x71bE63f3384f5fb98995898A86B02Fb2426c5788',
    bairroId: 'centro',
    bairroNome: 'Centro',
    criadoEm: '2026-03-16T14:20:00Z',
    justificativa:
      'Adequar calcadas de vias arteriais ao fluxo de pedestres e a parametros minimos de acessibilidade urbana.',
    issueId: '#51',
    urgencia: true,
    txHash: '0x999f111a777',
    impactedNeighborhoodIds: ['centro'],
    ci: {
      conflito: true,
      orcamento: false,
      constitucional: true,
      redacao: true,
    },
    oldText:
      'A largura minima das calcadas sera de 1,20m, observadas as condicoes de seguranca e acessibilidade fixadas em regulamento.',
    newText:
      'A largura minima das calcadas sera de 2,00m em vias arteriais e de 1,50m nas demais vias, observadas as condicoes de seguranca e acessibilidade fixadas em regulamento.',
    quorum: 2,
    votingEndsAt: '2026-03-30T14:20:00Z',
    votes: [
      {
        address: '0x71bE63f3384f5fb98995898A86B02Fb2426c5788',
        choice: 'favor',
        weight: 1,
        bairroId: 'centro',
        bairroNome: 'Centro',
        createdAt: '2026-03-16T15:00:00Z',
      },
      {
        address: CONCEICAO_CITIZEN_ADDRESS,
        choice: 'contra',
        weight: 0.6,
        bairroId: 'conceicao-itagua',
        bairroNome: 'Conceicao de Itagua',
        createdAt: '2026-03-16T19:00:00Z',
      },
    ],
    comments: [
      {
        id: 'comment-001',
        authorAddress: DEMO_CITIZEN_ADDRESS,
        createdAt: '2026-03-17T17:49:08.310Z',
        body: 'Teste local de comentario para validar a API.',
      },
    ],
    source: 'municipal',
  },
  {
    id: 'pr-103',
    kind: 'emenda',
    titulo: 'Incentiva captacao de agua da chuva',
    leiAlvoId: 'lei-3',
    leiAlvoNome: 'Politica Municipal de Meio Ambiente',
    artigoAlvoId: 'lei-3-art-8',
    artigoAlvoRotulo: 'Art. 8o',
    status: 'aprovado',
    autor: CONCEICAO_CITIZEN_ADDRESS,
    bairroId: 'conceicao-itagua',
    bairroNome: 'Conceicao de Itagua',
    criadoEm: '2026-02-28T10:00:00Z',
    justificativa:
      'Ampliar resiliencia hidrica e estimular adaptacao climatica com incentivo fiscal territorialmente auditavel.',
    issueId: '#32',
    urgencia: false,
    txHash: '0x111122223333',
    impactedNeighborhoodIds: ['conceicao-itagua', 'corrego-feijao'],
    ci: {
      conflito: true,
      orcamento: true,
      constitucional: true,
      redacao: true,
    },
    oldText:
      'O Municipio podera incentivar boas praticas ambientais por meio de programas de educacao e certificacao voluntaria.',
    newText:
      'O Municipio podera incentivar boas praticas ambientais por meio de programas de educacao, certificacao voluntaria e isencao parcial de IPTU para imoveis com captacao de agua da chuva, nos termos do regulamento.',
    quorum: 2,
    votingEndsAt: '2026-03-14T10:00:00Z',
    votes: [
      {
        address: CONCEICAO_CITIZEN_ADDRESS,
        choice: 'favor',
        weight: 1,
        bairroId: 'conceicao-itagua',
        bairroNome: 'Conceicao de Itagua',
        createdAt: '2026-03-01T11:00:00Z',
      },
      {
        address: '0x71bE63f3384f5fb98995898A86B02Fb2426c5788',
        choice: 'favor',
        weight: 0.6,
        bairroId: 'centro',
        bairroNome: 'Centro',
        createdAt: '2026-03-02T09:00:00Z',
      },
      {
        address: DEMO_CITIZEN_ADDRESS,
        choice: 'favor',
        weight: 0.3,
        bairroId: 'sape',
        bairroNome: 'Sape',
        createdAt: '2026-03-03T17:00:00Z',
      },
    ],
    comments: [
      {
        id: 'comment-2',
        authorAddress: DEMO_CITIZEN_ADDRESS,
        createdAt: '2026-03-02T14:10:00Z',
        body: 'Excelente precedente para futuros incentivos ligados a adaptacao climatica em bairros mais vulneraveis.',
      },
    ],
    source: 'municipal',
  },
  {
    id: 'pr-104',
    kind: 'variacao_local',
    titulo: 'Autoriza variacao local do Codigo de Obras no Sape',
    leiAlvoId: 'lei-2',
    leiAlvoNome: 'Codigo de Obras e Edificacoes',
    status: 'aprovado',
    autor: DEMO_CITIZEN_ADDRESS,
    bairroId: 'sape',
    bairroNome: 'Sape',
    criadoEm: '2026-03-08T09:00:00Z',
    justificativa:
      'Autorizar experimento territorial para uso misto de baixo impacto no Sape, com duracao limitada e trilha publica de resultados.',
    issueId: '#variacao-001',
    urgencia: false,
    txHash: '0xvariacao104',
    impactedNeighborhoodIds: ['sape'],
    ci: {
      conflito: true,
      orcamento: true,
      constitucional: true,
      redacao: true,
    },
    quorum: 1.2,
    votingEndsAt: '2026-03-09T20:00:00Z',
    closedAt: '2026-03-09T20:10:00Z',
    resolutionReason: 'aprovado_por_quorum',
    votes: [
      {
        address: DEMO_CITIZEN_ADDRESS,
        choice: 'favor',
        weight: 1,
        bairroId: 'sape',
        bairroNome: 'Sape',
        createdAt: '2026-03-08T11:00:00Z',
      },
      {
        address: '0x71bE63f3384f5fb98995898A86B02Fb2426c5788',
        choice: 'favor',
        weight: 0.6,
        bairroId: 'centro',
        bairroNome: 'Centro',
        createdAt: '2026-03-08T13:30:00Z',
      },
    ],
    comments: [],
    source: 'municipal',
    variationDraft: {
      nome: 'Zoneamento Misto - Sape',
      slug: 'sape-zoneamento-misto',
      objetivo:
        'Permitir comercio de baixo impacto em ruas residenciais para fortalecer a economia local sem perder controle urbano.',
      duracaoMeses: 6,
      bairroId: 'sape',
      bairroNome: 'Sape',
    },
  },
  {
    id: 'pr-201',
    kind: 'emenda',
    titulo: 'Nova versao: libera padarias de baixo impacto em vias locais',
    leiAlvoId: 'lei-fork-1',
    leiAlvoNome: 'Codigo de Obras (Variacao Sape)',
    artigoAlvoId: 'lei-fork-1-art-18',
    artigoAlvoRotulo: 'Art. 18',
    status: 'aberto',
    autor: DEMO_CITIZEN_ADDRESS,
    bairroId: 'sape',
    bairroNome: 'Sape',
    criadoEm: '2026-03-16T09:30:00Z',
    justificativa:
      'Permitir padarias e mercearias de pequeno porte perto das moradias para reduzir deslocamentos no bairro.',
    issueId: '#variacao-12',
    urgencia: false,
    txHash: '0xf0rkpr201',
    impactedNeighborhoodIds: ['sape'],
    ci: {
      conflito: true,
      orcamento: true,
      constitucional: true,
      redacao: null,
    },
    oldText:
      'Fica permitido comercio de baixo impacto em vias residenciais previamente definidas no plano local do experimento, mediante licenca simplificada.',
    newText:
      'Fica permitido comercio de baixo impacto, incluindo padarias artesanais, mercearias e servicos de conveniencia de pequeno porte, em vias residenciais previamente definidas no plano local do experimento, mediante licenca simplificada.',
    quorum: 1.2,
    votingEndsAt: '2026-03-24T09:30:00Z',
    votes: [],
    comments: [],
    forkId: 'fork-1',
    source: 'fork',
  },
];

const activities = [
  {
    id: 'activity-1',
    address: DEMO_CITIZEN_ADDRESS,
    tipo: 'mint_nft',
    titulo: 'NFT de cidadania emitido',
    descricao: 'Sua credencial civica foi emitida com sucesso e vinculada ao bairro Sape.',
    data: '2026-03-10T10:00:00Z',
    lida: true,
    link: '/perfil',
  },
  {
    id: 'activity-2',
    address: DEMO_CITIZEN_ADDRESS,
    tipo: 'voto_pendente',
    titulo: 'Votacao aberta no Centro com impacto adjacente',
    descricao: 'O PR-102 sobre largura de calcadas aceita seu voto com peso 0.6 por proximidade geografica.',
    data: '2026-03-17T09:00:00Z',
    lida: false,
    link: '/propostas/pr-102',
  },
  {
    id: 'activity-3',
    address: DEMO_CITIZEN_ADDRESS,
    tipo: 'pr_novo',
    titulo: 'Nova proposta na variacao do Sape',
    descricao: 'Sua variacao local recebeu uma proposta para liberar padarias de baixo impacto em vias locais.',
    data: '2026-03-16T09:45:00Z',
    lida: true,
    link: '/propostas/pr-201',
  },
  {
    id: 'activity-4',
    address: DEMO_CITIZEN_ADDRESS,
    tipo: 'comentario',
    titulo: 'Resposta ao seu comentario em telhados verdes',
    descricao: 'O autor do PR-101 respondeu ao seu comentario tecnico sobre equivalencia de cobertura.',
    data: '2026-03-15T18:10:00Z',
    lida: true,
    link: '/propostas/pr-101',
  },
  {
    id: 'activity-5',
    address: DEMO_CITIZEN_ADDRESS,
    tipo: 'pr_aprovado',
    titulo: 'PR ambiental aprovado no municipio',
    descricao: 'A proposta de incentivo a captacao de agua da chuva foi aprovada e gerou novo commit na lei ambiental.',
    data: '2026-03-14T20:00:00Z',
    lida: true,
    link: '/propostas/pr-103',
  },
];

export const seedStore = {
  neighborhoods,
  citizens,
  citizenshipRequests: [],
  laws,
  commits,
  proposals,
  forks,
  activities,
  events: [],
};
